services:
  system_monitor:
    build:
      context: .
      dockerfile: Dockerfile

    image: system_monitor:${IMAGE_TAG}

    container_name: system_monitor

    restart: unless-stopped

    network_mode: "host"