services:
  system-monitor:
    build:
      context: .
      dockerfile: Dockerfile

    image: system-monitor:${IMAGE_TAG}

    container_name: system-monitor

    restart: unless-stopped

    network_mode: "host"